export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/'
export const PROFILE_ROUTE = '/profile'
export const EVENT_ROUTE = '/event'
export const CONTACTS_ROUTE = '/contacts'